apiVersion: skaffold/v3
kind: Config

build:
  artifacts:
    - image: gopherproxyserver
      context: .
      docker:
        dockerfile: ./cmd/gopherproxyserver/Dockerfile.dev
      sync:
        infer:
          - "cmd/**/*"
          - "internal/**/*"

deploy:
  helm:
    releases:
      - name: "{{ .PROJECT_NAME }}"
        chartPath: ./helm
        namespace: "{{ .PROJECT_NAME }}-dev"
        createNamespace: true
        valuesFiles:
          - ./helm/services.yaml
