FROM golang:1.21.7-alpine AS setup

RUN mkdir -p /src/
WORKDIR /src/
RUN go install github.com/githubnemo/CompileDaemon@v1.4.0

FROM setup as build

COPY . . 
RUN go build -o ./bin/gopherproxyserver ./cmd/gopherproxyserver

ENTRYPOINT [ "CompileDaemon", "-directory=/src/", "-command=./bin/gopherproxyserver", "-build=go build -o ./bin/gopherproxyserver ./cmd/gopherproxyserver" ]
