services:
  - name: gopherproxy
    image: gopherproxyserver
    net:
      external: true
      host: gopherproxy.dev
      internalPort: 8080
    resources:
      limits:
        cpu: "1"
        memory: 256Mi
      requests:
        cpu: 10m
        memory: 64Mi
